from __future__ import annotations

import asyncio
from dataclasses import dataclass
from datetime import datetime
from typing import Any

import structlog

from app.core.config import get_settings

logger = structlog.get_logger()

NOTION_BLOCK_BATCH_LIMIT = 100
RATE_LIMIT_SLEEP = 0.4  # seconds between API calls (Notion 3 req/s limit)
MAX_API_RETRIES = 3


@dataclass
class ExportResult:
    root_page_id: str
    notion_url: str
    page_count: int


class NotionExportService:
    """Exports project documents to Notion as nested pages."""

    def _get_client(self) -> Any:
        from notion_client import AsyncClient

        settings = get_settings()
        if not settings.NOTION_API_TOKEN:
            raise ValueError("NOTION_API_TOKEN not configured")
        return AsyncClient(auth=settings.NOTION_API_TOKEN)

    async def export_project(
        self,
        project_id: str,
        project_name: str,
        documents: list[dict[str, str]],
        existing_page_id: str | None = None,
    ) -> ExportResult:
        """Export all documents to Notion under a parent page.

        Args:
            project_id: Project UUID string.
            project_name: Human-readable project name.
            documents: List of {"title": ..., "markdown": ...} dicts.
            existing_page_id: If set, re-export under existing parent page.

        Returns:
            ExportResult with root page ID, URL, and page count.
        """
        client = self._get_client()

        try:
            if existing_page_id:
                parent_id = existing_page_id
                await self._archive_child_pages(client, parent_id)
            else:
                parent_id = await self._create_parent_page(client, project_name)

            # Create sub-pages for each document
            doc_pages: list[dict[str, str]] = []
            for doc in documents:
                await asyncio.sleep(RATE_LIMIT_SLEEP)
                page_id = await self._create_document_page(
                    client, parent_id, doc["title"], doc["markdown"]
                )
                doc_pages.append({"title": doc["title"], "page_id": page_id})
                logger.info(
                    "created_notion_page",
                    title=doc["title"],
                    page_id=page_id,
                    project_id=project_id,
                )

            # Add table of contents to parent page
            await asyncio.sleep(RATE_LIMIT_SLEEP)
            toc_blocks = self._build_toc_blocks(doc_pages)
            await self._append_blocks(client, parent_id, toc_blocks)

            # Retrieve the parent page URL
            await asyncio.sleep(RATE_LIMIT_SLEEP)
            parent_page = await client.pages.retrieve(parent_id)
            notion_url = parent_page.get("url", f"https://notion.so/{parent_id.replace('-', '')}")

            return ExportResult(
                root_page_id=parent_id,
                notion_url=notion_url,
                page_count=len(doc_pages),
            )
        finally:
            await client.aclose()

    async def _create_parent_page(self, client: Any, project_name: str) -> str:
        settings = get_settings()
        parent_page_id = settings.NOTION_PARENT_PAGE_ID

        if parent_page_id:
            parent = {"page_id": parent_page_id}
        else:
            # Create at workspace root (database-less, requires integration on a page)
            # In practice, NOTION_PARENT_PAGE_ID should be set.
            parent = {"page_id": parent_page_id} if parent_page_id else {"workspace": True}

        now = datetime.now().strftime("%Y-%m-%d")
        page = await self._api_call_with_retry(
            client.pages.create,
            parent=parent,
            icon={"type": "emoji", "emoji": "📊"},
            properties={
                "title": {
                    "title": [{"text": {"content": f"{project_name} — AI Business Analysis"}}]
                }
            },
            children=[
                {
                    "object": "block",
                    "type": "callout",
                    "callout": {
                        "icon": {"type": "emoji", "emoji": "🤖"},
                        "rich_text": [
                            {"text": {"content": f"Generated by AI Business Analysis on {now}"}}
                        ],
                    },
                },
                {
                    "object": "block",
                    "type": "divider",
                    "divider": {},
                },
            ],
        )
        return page["id"]

    async def _create_document_page(
        self, client: Any, parent_id: str, title: str, markdown: str
    ) -> str:
        from md2notionpage import convert

        blocks = convert(markdown)

        # Create the page with the first batch of blocks (up to 100)
        first_batch = blocks[:NOTION_BLOCK_BATCH_LIMIT]
        remaining = blocks[NOTION_BLOCK_BATCH_LIMIT:]

        page = await self._api_call_with_retry(
            client.pages.create,
            parent={"page_id": parent_id},
            properties={
                "title": {"title": [{"text": {"content": title}}]}
            },
            children=first_batch,
        )
        page_id = page["id"]

        # Append remaining blocks in batches
        while remaining:
            await asyncio.sleep(RATE_LIMIT_SLEEP)
            batch = remaining[:NOTION_BLOCK_BATCH_LIMIT]
            remaining = remaining[NOTION_BLOCK_BATCH_LIMIT:]
            await self._append_blocks(client, page_id, batch)

        return page_id

    async def _append_blocks(self, client: Any, page_id: str, blocks: list[dict]) -> None:
        if not blocks:
            return
        await self._api_call_with_retry(
            client.blocks.children.append,
            block_id=page_id,
            children=blocks,
        )

    async def _archive_child_pages(self, client: Any, parent_id: str) -> None:
        """Archive all child pages under the parent (for re-export)."""
        response = await self._api_call_with_retry(
            client.blocks.children.list,
            block_id=parent_id,
        )
        for block in response.get("results", []):
            if block.get("type") == "child_page":
                await asyncio.sleep(RATE_LIMIT_SLEEP)
                await self._api_call_with_retry(
                    client.pages.update,
                    page_id=block["id"],
                    archived=True,
                )
                logger.info("archived_child_page", page_id=block["id"])

    def _build_toc_blocks(self, doc_pages: list[dict[str, str]]) -> list[dict]:
        """Build a heading + bulleted list linking to sub-pages."""
        blocks: list[dict] = [
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {
                    "rich_text": [{"text": {"content": "Documents"}}],
                },
            },
        ]
        for doc in doc_pages:
            blocks.append({
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {
                    "rich_text": [
                        {
                            "type": "mention",
                            "mention": {
                                "type": "page",
                                "page": {"id": doc["page_id"]},
                            },
                        }
                    ],
                },
            })
        return blocks

    async def _api_call_with_retry(self, func: Any, **kwargs: Any) -> Any:
        """Call a Notion API function with exponential backoff on rate limits."""
        from notion_client import APIResponseError

        for attempt in range(MAX_API_RETRIES):
            try:
                return await func(**kwargs)
            except APIResponseError as e:
                if e.status == 429 and attempt < MAX_API_RETRIES - 1:
                    wait = (2**attempt)  # 1s, 2s, 4s
                    logger.warning(
                        "notion_rate_limited",
                        attempt=attempt,
                        wait=wait,
                    )
                    await asyncio.sleep(wait)
                else:
                    raise
